[
	{
		"name": "Andrew Farrar",
		"title": "Web Developer",
		"portrait": "images/team/andrew_farrar.png",
		"portraitalt": "Andrew Farrar",
		"bio": "Andrew takes no prisoners.",
		"link": "",
	},
	{
		"name": "Jack Norcross",
		"title": "Legal Consultant",
		"portrait": "images/team/jack_norcross.png",
		"portraitalt": "Jack Norcross",
		"bio": "Jack is chillin' like a villain.",
		"link": "",
	},
	{
		"name": "Matt Fabian",
		"title": "Game Developer",
		"portrait": "images/team/matt_fabian.png",
		"portraitalt": "Matt Fabian",
		"bio": "Matt shot the Sheriff.",
		"link": "",
	},
	{
		"name": "Adam Cole",
		"title": "Sales Manager",
		"portrait": "images/team/adam_cole.png",
		"portraitalt": "Adam Cole",
		"bio": "Adam is keeping it real.",
		"link": "",
	},
	{
		"name": "Liam Norris",
		"title": "Web Developer",
		"portrait": "images/team/liam_norris.png",
		"portraitalt": "Liam Norris",
		"bio": "Liam has been around the world in 80 days.",
		"link": "",
	},
	{
		"name": "Daniel Johnson",
		"title": "Illustrator",
		"portrait": "images/team/daniel_johnson.png",
		"portraitalt": "Daniel Johnson",
		"bio": "Dan made the Kessel Run in 12 parsecs.",
		"link": "",
	},
	{
		"name": "Chris Vickery",
		"title": "Web Developer",
		"portrait": "images/team/chris_vickery.png",
		"portraitalt": "Chris Vickery",
		"bio": "Chris brakes for NOTHING.",
		"link": "",
	},
	{
		"name": "Jason Jefferson",
		"title": "System Administrator",
		"portrait": "images/team/jason_jefferson.png",
		"portraitalt": "Jason Jefferson",
		"bio": "Jason reached Oregon without losing any oxen.",
		"link": "",
	},
	{
		"name": "Mike Reinganum",
		"title": "Music Producer",
		"portrait": "images/team/mike_reinganum.png",
		"portraitalt": "Mike Reinganum",
		"bio": "Mike wrote a song for you.",
		"link": "",
	},
	{
		"name": "Work with us!",
		"title": "Many positions available",
		"portrait": {
			"src": "images/team/portrait-batsignal.png",
			"alt": "Open Positions",
		},
		"bio": "We're looking for talented, creative individuals to join our growing team.",
		"link": "http://www.linkedin.com/company/finix",
	},
];